<?php

namespace App\Console\Commands;

use App\Support\ApiReference;
use Illuminate\Console\Command;

/**
 * Write the public API reference (docs/api/) from the route table,
 * config/api_docs.php, the permission map and the English descriptions.
 *
 * The pages are generated, never edited by hand: an endpoint added to the
 * routes without an entry, or an entry the routes no longer have, fails
 * ApiReferenceTest, and --check (run by the same test) fails when the pages on
 * disk are not what this command would write today.
 */
class ApiDocsCommand extends Command
{
    protected $signature = 'pnlcs:api-docs {--check : Fail when the pages on disk differ from what would be written}';

    protected $description = 'Generate the API reference pages under docs/api from the route table';

    private const BANNER = '<!-- Generated by `php artisan pnlcs:api-docs` from config/api_docs.php. Do not edit by hand. -->';

    private const HOST = 'https://example.com';

    public function handle(): int
    {
        $files = $this->render();
        $stale = [];

        foreach ($files as $path => $content) {
            $full = base_path($path);

            if ($this->option('check')) {
                if (! is_file($full) || file_get_contents($full) !== $content) {
                    $stale[] = $path;
                }

                continue;
            }

            if (! is_dir(dirname($full))) {
                mkdir(dirname($full), 0755, true);
            }
            file_put_contents($full, $content);
        }

        if ($this->option('check')) {
            if ($stale !== []) {
                $this->error('The API reference is out of date. Run php artisan pnlcs:api-docs and commit the result:');
                foreach ($stale as $path) {
                    $this->line('  '.$path);
                }

                return self::FAILURE;
            }

            $this->info('The API reference is up to date ('.count($files).' files).');

            return self::SUCCESS;
        }

        $this->info('Wrote '.count($files).' files under docs/api.');

        return self::SUCCESS;
    }

    /**
     * Every generated file, path => content.
     *
     * @return array<string, string>
     */
    public function render(): array
    {
        $endpoints = ApiReference::endpoints();
        $bySection = array_fill_keys(array_keys(ApiReference::SECTIONS), []);

        foreach ($endpoints as $action => $endpoint) {
            $bySection[$endpoint['spec']['section'] ?? 'system'][$action] = $endpoint;
        }

        $files = [];
        foreach ($bySection as $section => $rows) {
            $files["docs/api/{$section}.md"] = $this->sectionPage($section, $rows);
        }
        $files['docs/api/all-endpoints.md'] = $this->indexPage($bySection);
        $files['docs/api/openapi.json'] = $this->openApi($endpoints);

        return $files;
    }

    private function sectionPage(string $section, array $rows): string
    {
        $title = ApiReference::SECTIONS[$section];
        $out = [self::BANNER, '', '# '.$title, ''];
        $out[] = count($rows).' endpoints. Authentication, errors, paging and rate limits are described once, in the [API overview](index.md).';
        $out[] = '';
        $out[] = '| Action | Method | Description |';
        $out[] = '|---|---|---|';
        foreach ($rows as $action => $endpoint) {
            $out[] = '| [`'.$action.'`](#'.$action.') | '.$endpoint['method'].' | '.$this->cell($this->description($action)).' |';
        }
        $out[] = '';

        foreach ($rows as $action => $endpoint) {
            $out = array_merge($out, $this->endpointBlock($action, $endpoint));
        }

        return implode("\n", $out)."\n";
    }

    private function endpointBlock(string $action, array $endpoint): array
    {
        $spec = $endpoint['spec'];
        $permission = ApiReference::permission($endpoint);
        $out = [
            '## '.$action,
            '',
            $this->description($action).'.',
            '',
            '`'.$endpoint['method'].' /api/v1/'.$action.'`',
            '',
            '**Permission:** '.($permission !== null ? '`'.$permission.'`' : 'full administrator only'),
            '',
        ];

        if (isset($spec['unavailable'])) {
            $out[] = '!!! warning "Not available"';
            $out[] = '    '.$spec['unavailable'];
            $out[] = '';

            return $out;
        }

        $params = ApiReference::params($spec);
        $out[] = '**Parameters**';
        $out[] = '';
        if ($params === []) {
            $out[] = 'None.';
        } else {
            $out[] = '| Name | Type | Required | Description |';
            $out[] = '|---|---|---|---|';
            foreach ($params as $p) {
                $out[] = '| `'.$p['name'].'` | '.$p['type'].' | '.($p['required'] ? 'yes' : 'no').' | '.$this->cell($p['description']).' |';
            }
        }
        $out[] = '';
        if (isset($spec['one_of'])) {
            $out[] = 'One of '.implode(' or ', array_map(fn ($n) => '`'.$n.'`', $spec['one_of'])).' is required.';
            $out[] = '';
        }

        $out[] = '**Response**';
        $out[] = '';
        $out[] = '| Field | Description |';
        $out[] = '|---|---|';
        $out[] = '| `result` | `success` |';
        if (! empty($spec['list'])) {
            $out[] = '| `totalresults` | integer: rows matching the filters |';
            $out[] = '| `startnumber` | integer: where this page starts |';
            $out[] = '| `numreturned` | integer: rows on this page |';
            $out[] = '| `data` | array: the rows |';
        }
        foreach ($spec['returns'] ?? [] as $field => $description) {
            $out[] = '| `'.$field.'` | '.$this->cell($description).' |';
        }
        $out[] = '';

        if (! empty($spec['errors'])) {
            $out[] = '**Errors**';
            $out[] = '';
            $out[] = '| Status | When |';
            $out[] = '|---|---|';
            foreach ($spec['errors'] as $status => $when) {
                $out[] = '| '.$status.' | '.$this->cell($when).' |';
            }
            $out[] = '';
        }

        if (! empty($spec['notes'])) {
            $out[] = '!!! note';
            $out[] = '    '.$spec['notes'];
            $out[] = '';
        }

        $out[] = '**Example**';
        $out[] = '';
        $out[] = '```bash';
        $out = array_merge($out, $this->curl($action, $endpoint));
        $out[] = '```';
        $out[] = '';

        return $out;
    }

    /** A curl call that works as written, once the host and credential are filled in. */
    private function curl(string $action, array $endpoint): array
    {
        $spec = $endpoint['spec'];
        $get = $endpoint['method'] === 'GET';
        $lines = [($get ? 'curl -G ' : 'curl -X POST ').self::HOST.'/api/v1/'.$action];
        $lines[] = '  -H "X-API-Key: $PNLCS_IDENTIFIER"';
        $lines[] = '  -H "X-API-Secret: $PNLCS_SECRET"';

        foreach (ApiReference::example($spec) as $name => $value) {
            $lines[] = '  --data-urlencode "'.$name.'='.$value.'"';
        }

        $last = count($lines) - 1;
        foreach ($lines as $i => $line) {
            if ($i < $last) {
                $lines[$i] = $line.' \\';
            }
        }

        return $lines;
    }

    private function indexPage(array $bySection): string
    {
        $all = [];
        foreach ($bySection as $section => $rows) {
            foreach ($rows as $action => $endpoint) {
                $all[$action] = [$section, $endpoint];
            }
        }
        ksort($all);

        $out = [self::BANNER, '', '# All endpoints', ''];
        $out[] = count($all).' endpoints, in alphabetical order. Each links to its full description.';
        $out[] = '';
        $out[] = '| Action | Method | Section | Description |';
        $out[] = '|---|---|---|---|';
        foreach ($all as $action => [$section, $endpoint]) {
            $out[] = '| [`'.$action.'`]('.$section.'.md#'.$action.') | '.$endpoint['method'].' | '.ApiReference::SECTIONS[$section].' | '.$this->cell($this->description($action)).' |';
        }

        return implode("\n", $out)."\n";
    }

    private function openApi(array $endpoints): string
    {
        $types = [
            'integer' => ['type' => 'integer'],
            'number' => ['type' => 'number'],
            'boolean' => ['type' => 'boolean'],
            'date' => ['type' => 'string', 'format' => 'date'],
            'email' => ['type' => 'string', 'format' => 'email'],
            'url' => ['type' => 'string', 'format' => 'uri'],
            'array' => ['type' => 'array', 'items' => ['type' => 'string']],
            'object' => ['type' => 'object'],
            'string' => ['type' => 'string'],
        ];

        $paths = [];
        $requestSchemas = [];
        foreach ($endpoints as $action => $endpoint) {
            $spec = $endpoint['spec'];
            $operation = [
                'operationId' => $action,
                'summary' => $this->description($action),
                'tags' => [ApiReference::SECTIONS[$spec['section'] ?? 'system']],
            ];

            $description = trim(($spec['unavailable'] ?? '').' '.($spec['notes'] ?? ''));
            $permission = ApiReference::permission($endpoint);
            $operation['description'] = trim($description.' Permission: '.($permission ?? 'full administrator only').'.');

            $params = ApiReference::params($spec);
            if ($endpoint['method'] === 'GET') {
                $operation['parameters'] = array_map(fn ($p) => [
                    'name' => $p['type'] === 'array' ? $p['name'].'[]' : $p['name'],
                    'in' => 'query',
                    'required' => $p['required'],
                    'description' => $p['description'],
                    'schema' => $types[$p['type']] ?? ['type' => 'string'],
                ], $params);
            } elseif ($params !== []) {
                $properties = [];
                $required = [];
                foreach ($params as $p) {
                    $properties[$p['name']] = ($types[$p['type']] ?? ['type' => 'string']) + ['description' => $p['description']];
                    if ($p['required']) {
                        $required[] = $p['name'];
                    }
                }
                $schema = ['type' => 'object', 'properties' => $properties];
                if ($required !== []) {
                    $schema['required'] = $required;
                }
                $requestSchemas[$action] = $schema;
                $ref = ['$ref' => '#/components/schemas/'.$action];
                $operation['requestBody'] = [
                    'required' => $required !== [],
                    'content' => [
                        'application/x-www-form-urlencoded' => ['schema' => $ref],
                        'application/json' => ['schema' => $ref],
                    ],
                ];
            }

            $responses = ['200' => ['description' => 'result is success', 'content' => ['application/json' => ['schema' => ['$ref' => '#/components/schemas/Success']]]]];
            foreach ($spec['errors'] ?? [] as $status => $when) {
                $responses[(string) $status] = ['description' => $when, 'content' => ['application/json' => ['schema' => ['$ref' => '#/components/schemas/Error']]]];
            }
            if (isset($spec['unavailable'])) {
                $code = str_contains($spec['unavailable'], '403') ? '403' : '501';
                $responses = [$code => ['description' => $spec['unavailable'], 'content' => ['application/json' => ['schema' => ['$ref' => '#/components/schemas/Error']]]]];
            }
            $operation['responses'] = $responses;

            $paths['/api/v1/'.$action][strtolower($endpoint['method'])] = $operation;
        }

        $document = [
            'openapi' => '3.1.0',
            'info' => [
                'title' => 'PNLCS API',
                'version' => '1.0.0',
                'description' => 'The PNLCS billing and client management API. Every call is answered as the staff account the credential belongs to, with that account\'s permissions.',
                'license' => ['name' => 'MIT', 'identifier' => 'MIT'],
            ],
            'servers' => [['url' => '{baseUrl}', 'variables' => ['baseUrl' => ['default' => self::HOST, 'description' => 'Your PNLCS address']]]],
            'security' => [['apiKey' => [], 'apiSecret' => []]],
            'tags' => array_map(fn ($title) => ['name' => $title], array_values(ApiReference::SECTIONS)),
            'paths' => $paths,
            'components' => [
                'securitySchemes' => [
                    'apiKey' => ['type' => 'apiKey', 'in' => 'header', 'name' => 'X-API-Key', 'description' => 'The credential identifier.'],
                    'apiSecret' => ['type' => 'apiKey', 'in' => 'header', 'name' => 'X-API-Secret', 'description' => 'The credential secret.'],
                ],
                'schemas' => [
                    'Success' => ['type' => 'object', 'properties' => ['result' => ['type' => 'string', 'const' => 'success']], 'required' => ['result'], 'additionalProperties' => true],
                    'Error' => ['type' => 'object', 'properties' => ['result' => ['type' => 'string', 'const' => 'error'], 'message' => ['type' => 'string']], 'required' => ['result', 'message']],
                ] + $requestSchemas,
            ],
        ];

        return json_encode($document, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)."\n";
    }

    /**
     * The shipped English description. Read from the file rather than through
     * the translator, whose database overrides would make the pages depend on
     * whichever installation ran the command.
     */
    private function description(string $action): string
    {
        static $english = null;
        $english ??= (array) require lang_path('en/admin.php');

        return (string) ($english['api_docs.desc_'.$action] ?? $action);
    }

    /** Text safe inside a Markdown table cell. */
    private function cell(string $text): string
    {
        return str_replace(['|', "\n"], ['\\|', ' '], $text);
    }
}
