// Writes docs/mcp/tools.md from lib/tools.js, so the documentation lists the
// tools the server really offers, with the arguments it really takes.
//
//   node scripts/docs.mjs          write the page
//   node scripts/docs.mjs --check  exit 1 when the page on disk is stale
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { toolset } from '../lib/tools.js';

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, '..', '..', 'docs', 'mcp', 'tools.md');

const cell = (text) => String(text).replaceAll('|', '\\|').replaceAll('\n', ' ');

function block(tool) {
  const required = new Set(tool.required ?? []);
  const lines = [
    `### ${tool.name}`,
    '',
    cell(tool.description),
    '',
    `Calls the API action [\`${tool.action}\`](../api/all-endpoints.md) with ${tool.method ?? 'GET'}.`,
    '',
  ];
  const args = Object.entries(tool.args);
  if (args.length === 0) {
    lines.push('No arguments.', '');
  } else {
    lines.push('| Argument | Type | Required | Description |', '|---|---|---|---|');
    for (const [name, schema] of args) {
      lines.push(`| \`${name}\` | ${schema.type} | ${required.has(name) ? 'yes' : 'no'} | ${cell(schema.description ?? '')} |`);
    }
    lines.push('');
  }
  if (tool.fixed) {
    const fixed = Object.entries(tool.fixed).map(([k, v]) => `\`${k}=${v}\``).join(', ');
    lines.push(`Always sends ${fixed}.`, '');
  }
  return lines;
}

export function render() {
  const all = toolset(true);
  const reads = toolset(false);
  const writes = all.filter((t) => !reads.includes(t));
  const out = [
    '<!-- Generated by `node mcp/scripts/docs.mjs` from mcp/lib/tools.js. Do not edit by hand. -->',
    '',
    '# MCP tools',
    '',
    `${all.length} tools: ${reads.length} that read, always available, and ${writes.length} that change something, offered only with \`PNLCS_ALLOW_WRITES=1\`.`,
    'Each tool is one [API action](../api/index.md) and needs the same permission as that action.',
    '',
    '## Read tools',
    '',
  ];
  for (const tool of reads) out.push(...block(tool));
  out.push('## Write tools', '', '!!! warning', '    These exist only when `PNLCS_ALLOW_WRITES=1` is set. Without it a call to one is refused before anything is sent to PNLCS.', '');
  for (const tool of writes) out.push(...block(tool));
  return out.join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const page = render();
  if (process.argv.includes('--check')) {
    let current = '';
    try { current = readFileSync(target, 'utf8'); } catch { /* missing counts as stale */ }
    if (current !== page) {
      console.error('docs/mcp/tools.md is out of date: run node mcp/scripts/docs.mjs');
      process.exit(1);
    }
    console.log('docs/mcp/tools.md is up to date.');
  } else {
    writeFileSync(target, page);
    console.log(`Wrote ${target}`);
  }
}
