<p>This policy explains how {{ \App\Http\Controllers\LegalController::partyName($company, $tr) }} handles personal data <strong>about our own customers</strong>. It covers our obligations under the EU General Data Protection Regulation (GDPR), the UK GDPR, Turkish Law No. 6698 on the Protection of Personal Data (KVKK) and the California Consumer Privacy Act as amended (CCPA/CPRA).</p>

<div class="legal-note">
    <p>This policy concerns data for which <strong>we are the controller</strong>: your account, your invoices, your support correspondence. For visitor data you host on your own site, <strong>you are the controller and we are only a processor</strong> — that relationship is governed by the <a href="{{ route('legal.show', 'dpa') }}">Data Processing Addendum</a>.</p>
</div>

<h2>1. Controller</h2>
@include('legal.partials.seller')

<h2>2. Data we process</h2>
<table>
    <thead><tr><th>Category</th><th>Data</th><th>Source</th></tr></thead>
    <tbody>
        <tr><td>Identity and contact</td><td>Name, company name, email, telephone, address, country</td><td>From you, at sign-up</td></tr>
        <tr><td>Billing and financial</td><td>Tax office and number, invoice records, payment amounts and dates, transfer references</td><td>From you and from our bank</td></tr>
        <tr><td>Account and service</td><td>Username, password hash, service and domain records, resource usage</td><td>Generated by our systems</td></tr>
        <tr><td>Domain registration</td><td>Name, address, email and telephone required for registration</td><td>From you; passed to the registrar</td></tr>
        <tr><td>Technical records</td><td>IP address, browser information, sign-in times, server and security logs</td><td>Collected automatically</td></tr>
        <tr><td>Support</td><td>Tickets, email correspondence, attachments</td><td>From you</td></tr>
    </tbody>
</table>
<p>We <strong>do not collect or store card details.</strong> Card payments run through a PCI DSS compliant payment institution; the card number, expiry date and security code never enter our systems. We receive only the outcome of the payment (authorised or declined), the amount, and identifiers such as the card type and last four digits that let us match the transaction.</p>

<h2>3. Purposes and lawful bases</h2>
<table>
    <thead><tr><th>Purpose</th><th>Lawful basis (GDPR Art. 6 / KVKK Art. 5)</th></tr></thead>
    <tbody>
        <tr><td>Provisioning, delivering and managing the service</td><td>Performance of a contract</td></tr>
        <tr><td>Invoicing, collection and accounting</td><td>Legal obligation and performance of a contract</td></tr>
        <tr><td>Domain registration and WHOIS obligations</td><td>Performance of a contract and legal obligation</td></tr>
        <tr><td>Providing support</td><td>Performance of a contract</td></tr>
        <tr><td>Network and system security, preventing abuse</td><td>Legitimate interests</td></tr>
        <tr><td>Mandatory service notices (outages, maintenance, invoices)</td><td>Performance of a contract</td></tr>
        <tr><td>Marketing emails (offers, announcements)</td><td>Consent — withdrawable at any time</td></tr>
        <tr><td>Establishing, exercising or defending legal claims</td><td>Legitimate interests and legal obligation</td></tr>
    </tbody>
</table>
<p>Where we rely on legitimate interests we have assessed that our interest does not override your rights and freedoms. You may request a summary of that assessment.</p>

<h2>4. Retention</h2>
<table>
    <thead><tr><th>Data</th><th>Period</th><th>Reason</th></tr></thead>
    <tbody>
        <tr><td>Invoices and accounting records</td><td>10 years</td><td>Turkish Commercial Code and Tax Procedure Law</td></tr>
        <tr><td>Account and contract records</td><td>10 years after the service ends</td><td>Limitation period</td></tr>
        <tr><td>Traffic and access logs</td><td>2 years</td><td>Turkish Law No. 5651</td></tr>
        <tr><td>Server and security logs</td><td>90 days</td><td>Legitimate interest — incident investigation</td></tr>
        <tr><td>Support correspondence</td><td>3 years after closure</td><td>Service quality and potential disputes</td></tr>
        <tr><td>Content of a suspended account</td><td>30 days</td><td>To allow recovery</td></tr>
        <tr><td>Marketing consent records</td><td>3 years after withdrawal</td><td>To evidence that consent was withdrawn</td></tr>
    </tbody>
</table>

<h2>5. Disclosure and transfers</h2>
<p>We do not sell your data. We share it only with parties necessary to deliver the service, and only to the extent needed:</p>
<ul>
    <li><strong>Domain registrars and registries</strong> — for domains you register, limited to the registration data ICANN and the registry require.</li>
    <li><strong>Our data centre and infrastructure provider</strong> — our servers are hosted in Germany (Hetzner Online GmbH), within the EU data protection regime.</li>
    <li><strong>Our bank and our payment institution</strong> — only what is needed to take the payment. In respect of card data the payment institution acts as an independent controller under its own privacy policy.</li>
    <li><strong>Our accountant and auditors</strong> — for accounting and tax obligations.</li>
    <li><strong>Competent public authorities</strong> — only on a legally binding and properly issued request.</li>
</ul>
<p>Where a transfer outside the EEA or Türkiye is necessary, it is made on the basis of the European Commission's Standard Contractual Clauses or an adequacy decision, and in accordance with the transfer provisions of Turkish Law No. 6698.</p>

<h2>6. Security</h2>
<ul>
    <li>All site and panel traffic is encrypted with TLS; certificates renew automatically.</li>
    <li>Passwords are stored as irreversible hashes and are never held in plain text.</li>
    <li>Administrative access is key-based and protected by two-factor authentication.</li>
    <li>Each customer account is isolated from the others at operating-system level.</li>
    <li>A host firewall, ModSecurity and malware scanning are active.</li>
    <li>Database backups are taken daily and held in a restricted directory.</li>
</ul>
<p>In the event of a breach affecting your personal data we notify the supervisory authority within <strong>72 hours</strong> and affected individuals as soon as reasonably possible.</p>

<h2>7. Your rights</h2>
<p>Depending on where you live, you have the right to:</p>
<ul>
    <li>know whether we process your personal data and obtain a copy,</li>
    <li>have inaccurate or incomplete data corrected,</li>
    <li>have data erased, where we are not legally required to keep it,</li>
    <li>restrict processing,</li>
    <li>receive your data in a structured, machine-readable format (portability),</li>
    <li>object to processing based on legitimate interests,</li>
    <li>withdraw consent where processing is based on it,</li>
    <li>object to a decision produced solely by automated analysis that affects you adversely,</li>
    <li>claim compensation for damage caused by unlawful processing.</li>
</ul>
<p>If you are a California resident, the CCPA/CPRA gives you the right to know the categories we collect, to request deletion, and to opt out of sale or sharing. <strong>We do not sell your personal information and do not share it for advertising.</strong> You will not be discriminated against for exercising these rights.</p>

<h3>How to exercise them</h3>
<p>Write to <a href="mailto:{{ $company['kvkk_email'] }}">{{ $company['kvkk_email'] }}</a>. We respond within <strong>30 days</strong>. Complex requests may be extended once, and we will tell you if that happens. Requests are free; we may charge a reasonable fee for manifestly unfounded or repetitive ones.</p>
<p>If you are not satisfied with our response you may complain to your national data protection authority. In Türkiye that is the <strong>Personal Data Protection Authority</strong> (kvkk.gov.tr).</p>

<h2>8. Cookies</h2>
<p>The cookies this site sets and how to control them are described in the <a href="{{ route('legal.show', 'cookies') }}">Cookie Policy</a>.</p>

<h2>9. Children</h2>
<p>Our services are not directed at anyone under 18 and we do not knowingly collect personal data from children. Where we learn of such data, we delete it without delay.</p>

<h2>10. Changes</h2>
<p>We may update this policy. Material changes are notified by email at least 30 days before they take effect. The effective date at the foot of the page tells you which version applies.</p>
