<?php

/*
 * Hand-written "key parameters" strings for the API reference screen.
 *
 * The endpoint LIST on that screen is not written here or anywhere else by
 * hand - it is read from the live route table, so it cannot drift from the
 * code again (it once documented 26 endpoints that did not exist and left 91
 * real ones out). Only these short parameter hints are curated; an endpoint
 * missing from this file still appears on the screen, just without a hint.
 */
return [
    'acceptorder' => 'orderid (required)',
    'acceptquote' => 'quoteid (required)',
    'addannouncement' => 'title, announcement (required), published (default true)',
    'addclient' => 'firstname, lastname, email, password2 (optional - opens a portal login), address1, city, country, phonenumber',
    'addclientnote' => 'userid (or clientid), note (required), sticky',
    'addcontact' => 'clientid, email, firstname, lastname (required)',
    'addcredit' => 'clientid, description, amount (required)',
    'addinvoicepayment' => 'invoiceid, transid, amount (required), gateway - recorded with today\'s date',
    'addorder' => 'clientid, pid[], billingcycle[], paymentmethod (required)',
    'addproduct' => 'name, gid (required), type (hostingaccount|reselleraccount|server|other), paytype (free|onetime|recurring), description, module, servergroupid, autosetup (order|payment|on), pricing[currencyid][monthly..triennially]',
    'addprojectmessage' => 'projectid, message (required) - signed by the credential\'s owner',
    'addprojecttask' => 'projectid, task (required), notes, due_date',
    'addticketreply' => 'ticketid, message (required); adminusername (any value) replies as staff, signed by the credential\'s owner; without it the reply is the customer\'s (userid)',
    'addtransaction' => 'userid, description (required), amountin, amountout, invoiceid (must be that client\'s), transid, gateway',
    'applycredit' => 'invoiceid, amount (required), clientid (optional, must own the invoice)',
    'cancelorder' => 'orderid (required)',
    'createinvoice' => 'userid (required), items[] {description, amount, taxed} or itemdescription1/itemamount1/itemtaxed1..., date, duedate, paymentmethod, status (draft|unpaid|paid), notes',
    'createproject' => 'title, clientid (required), status (pending|in_progress|completed|cancelled), due_date, description - owned by the credential\'s owner',
    'createquote' => 'userid (required), subject, validuntil, items[] {description, quantity, unit_price, discount, taxable}',
    'deleteclient' => 'clientid (required)',
    'deletecontact' => 'contactid (required)',
    'deleteorder' => 'orderid (required)',
    'deleteprojecttask' => 'taskid (required)',
    'deletequote' => 'quoteid (required)',
    'deleteticket' => 'ticketid (required)',
    'deleteticketreply' => 'replyid (required)',
    'domainregister' => 'domainid (required)',
    'domainrelease' => 'not implemented (501) - request the transfer code with domainrequestepp',
    'domainrenew' => 'domainid (required)',
    'domaintransfer' => 'domainid (required)',
    'domainupdatelockingstatus' => 'domainid, lockstatus (required)',
    'domainwhois' => 'domain (required) - answers status available or unavailable; 503 when nobody could be asked',
    'fraudorder' => 'orderid (required)',
    'getannouncements' => 'limitnum, limitstart',
    'getclientpassword' => 'not supported (403) - passwords are stored hashed',
    'getclients' => 'search, status, group_id, orderby (id|first_name|last_name|email|company_name|status|created_at), sorting (ASC|DESC), limitnum, limitstart',
    'getclientsaddons' => 'clientid, serviceid',
    'getclientsdetails' => 'clientid or email (required)',
    'getclientsdomains' => 'clientid, domainid, domain, status, limitnum, limitstart',
    'getclientsproducts' => 'clientid, serviceid, pid, domain, status, limitnum, limitstart',
    'getcontacts' => 'userid (required)',
    'getinvoice' => 'invoiceid (required)',
    'getinvoices' => 'userid, status, limitnum, limitstart',
    'getorders' => 'userid, status, limitnum, limitstart',
    'getproducts' => 'pid, gid, module',
    'getproject' => 'projectid (required)',
    'getprojects' => 'limitnum, limitstart',
    'getquotes' => 'userid, status, limitnum, limitstart',
    'getticket' => 'ticketid (required)',
    'gettickets' => 'clientid, deptid, status, limitnum, limitstart',
    'gettransactions' => 'clientid, invoiceid, limitnum, limitstart',
    'modulechangepackage' => 'serviceid (required)',
    'modulechangepw' => 'serviceid (required)',
    'modulecreate' => 'serviceid (required)',
    'modulesuspend' => 'serviceid (required)',
    'moduleterminate' => 'serviceid (required)',
    'moduleunsuspend' => 'serviceid (required)',
    'openticket' => 'deptid, subject, message, email (required), clientid, name, priority (low|medium|high|critical), adminusername (opened by staff)',
    'pendingorder' => 'orderid (required)',
    'sendadminemail' => 'customsubject, custommessage (required), deptid - to every active member of staff, or those handling that department',
    'sendemail' => 'messagename (a template: invoice created, invoice payment confirmation, invoice reminder, invoice overdue, service welcome email, service suspension, service unsuspension, service termination, order confirmation, domain registration confirmation, domain renewal reminder, account signup email) and id; or customsubject, custommessage, id, customtype (general|invoice|product|domain)',
    'sendquote' => 'quoteid (required)',
    'updateclient' => 'clientid (required), firstname, lastname, email, companyname, address1, city, state, postcode, country, phonenumber, status (active|inactive|closed)',
    'updateclientdomain' => 'domainid (required), status, expirydate, nextduedate, regdate, registrar, dns_management, email_forwarding, id_protection, payment_method, notes',
    'updateclientproduct' => 'serviceid (required), status, domain, username, password, next_due_date, billing_cycle, notes',
    'updatecontact' => 'contactid (required)',
    'updateinvoice' => 'invoiceid (required), status, date, duedate, paymentmethod, notes; status paid records the payment (transid, gateway), cancelled refunds credit',
    'updateproject' => 'projectid (required), title, description, status (pending|in_progress|completed|cancelled), due_date',
    'updateprojecttask' => 'taskid (required), task, notes, completed, due_date',
    'updatequote' => 'quoteid (required), status (Draft|Sent|Accepted|Declined), validuntil, notes, customer_notes, proposal',
    'updateticket' => 'ticketid (required), status (a configured ticket status), subject, priority (low|medium|high|critical), deptid, flag (admin id)',
    'validatelogin' => 'email, password (required)',
    'deleteuserclient' => 'userid, clientid (required) - takes the login off that account; the login itself stays',
    'blockticketsender' => 'ticketid (required), delete - adds the sender to the ticket spam filter',
    'getpaymethods' => 'clientid (required)',
    'updatepaymethod' => 'clientid, paymethodid (required), set_as_default, description',
    'deletepaymethod' => 'clientid, paymethodid (required)',
    'addpaymethod' => 'not implemented (501) - a card has to be added by the customer at the gateway\'s own form (3-D Secure); card numbers never pass through PNLCS',
    'resetpassword' => 'email or id (a login\'s user id) - sends the customer the reset link',
    'activatemodule' => 'moduleType (server|gateway|registrar|ssl|addon), moduleName (required)',
    'deactivatemodule' => 'moduleType (server|gateway|registrar|ssl|addon), moduleName (required) - a server or SSL module in use stays on',
    'logactivity' => 'description (required), clientid - signed by the credential\'s owner',
    'addcancelrequest' => 'serviceid (required), type (Immediate|End of Billing Period), reason',
    'geninvoices' => 'no parameters - runs for every due service; filters are refused',
    'getmodulequeue' => 'status (pending|completed|failed|cancelled; default pending and failed), limitnum, limitstart',
    'domaintoggleidprotect' => 'domainid (required), idprotect (true|false; flips it when left out)',
    'createorupdatetld' => 'extension (required), register_price, transfer_price, renew_price, enabled, sort_order',
    'updatetodoitem' => 'itemid (required), title, description, status (New|In Progress|Completed|Deferred), due_date',
    'addbannedip' => 'ip (required: an address, or a prefix ending in *), reason',
    'createoauthcredential' => 'description - owned by the credential\'s owner; needs manage staff',
    'mergeticket' => 'ticketid, mergeid (required, different tickets) - replies and notes move to mergeid',
    'updatemoduleconfiguration' => 'moduleType (gateway|registrar|ssl|addon), moduleName, parameters[name] (required) - a blank password keeps the stored one',
    'getmoduleconfigurationparameters' => 'moduleType (server|gateway|registrar|ssl|addon), moduleName (required) - field names, labels and types, never stored values',
    'triggernotificationevent' => 'title, message (required), url, notification_identifier - sent through the rules set for the api.custom event',
    'starttasktimer' => 'taskid (required), projectid',
    'endtasktimer' => 'timerid (required)',
    'createssotoken' => 'client_id (required), user_id, destination (clientarea:homepage|invoices|services|domains|tickets|product_details + service_id|domain_details + domain_id|sso:custom_redirect + sso_redirect_path) - a one-use link, valid 60 seconds',
    'createclientinvite' => 'client_id, email (required), permissions (all, or a comma list of profile, contacts, products, manageproducts, productsso, domains, managedomains, invoices, quotes, tickets, affiliates, emails, orders)',
    'getuserpermissions' => 'user_id, client_id (required)',
    'updateuserpermissions' => 'user_id, client_id, permissions (required: all, or a comma list)',
    'modulecustom' => 'serviceid, func_name (required) - a function the service\'s server module lists in customFunctions()',
];
